services:
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: appdb
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      DATABASE_URL: sqlite:///../data/app.db
    ports:
      - "5000:5000"
    # depends_on:
    #   - db
    volumes:
      - ./app:/app
      - ./data:/data
      - ./migrations:/migrations
      - ./instance:/instance
volumes:
  db-data:
