"""add rise_probability_summary

Revision ID: 3a7feb27002f
Revises: 
Create Date: 2025-10-27 00:23:59.085779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7feb27002f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rise_probability_summary',
    sa.Column('stock_code', sa.String(length=8), primary_key=True, nullable=False),
    sa.Column('prob_model1', sa.Float(), nullable=True),
    sa.Column('prob_model2', sa.Float(), nullable=True),
    sa.Column('prob_model3', sa.Float(), nullable=True),
    sa.Column('prob_model4', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False)
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    op.drop_table('rise_probability_summary')
    # ### end Alembic commands ###
