"""add auc_model columns to RiseProbabilitySummary

Revision ID: 9ed5b49e054f
Revises: 3a7feb27002f
Create Date: 2025-10-27 22:45:32.164409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed5b49e054f'
down_revision = '3a7feb27002f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rise_probability_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auc_model1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('auc_model2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('auc_model3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('auc_model4', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rise_probability_summary', schema=None) as batch_op:
        batch_op.drop_column('auc_model4')
        batch_op.drop_column('auc_model3')
        batch_op.drop_column('auc_model2')
        batch_op.drop_column('auc_model1')

    # ### end Alembic commands ###
